---
title: "Baza wiedzy"
site: distill::distill_website
---

<span> <b> Gdzie zacz szukanie wiedzy, og贸lnoprzydatne serwisy</b>


<table style="width:100%">



<tr>
<th>
Google Scholar
</th>
<th>
Pierwsze miejsce w kt贸re nale偶y zajrze przy szukaniu artyku贸w naukowych
<th>
https://scholar.google.pl/ 
</th>
</tr>

<tr>
<th>Semantic Scholar</th>
<th>Alternatywa dla G.Scholar</th>

<th>https://www.semanticscholar.org/</th>
</tr>

<tr>
<th>Microsoft Academic</th>
<th>Alternatywa dla G.Scholar</th>

<th>https://academic.microsoft.com/home</th>
</tr>


<tr>
<th> Academia</th>

<th>Spoecznociowa baza artyku贸w</th>
<th>https://www.academia.edu/</th>
</tr>

<tr>
<th> ResearchGate</th>
<th> Spoecznociowa baza artyku贸w</th>
<th>https://www.researchgate.net/</th>
</tr>

<tr>
<th>Predatory Journals</th>
<th>Lista pism, kt贸rych nale偶y unika</th>

<th>https://predatoryjournals.com/journals/  </th>
</tr>

<tr>
<th>
Punktoza </th>
 
<th>Portal pozwalajcy sprawdzi aktualn punktacj czasopism wg list ministerialnych </th>
<th>https://punktoza.pl/ </th>
</tr>

<tr>
<th>Listy ministerialne punktowanych pism</th>
<th></th>
<th>https://listymnisw.pl/  </th>
</tr>

<tr>
<th>Otwarte Zasoby</th>
<th>Strona zbierajca zasoby na otwartej licencji</th>
<th>https://otwartezasoby.pl/ </th>
</tr>

<tr>
<th>Open Culture</th>
<th>Strona zbierajca zasoby na otwartej licencji</th>
<th>https://www.openculture.com/</th>
</tr>

<tr>
<th>Archive.com</th>
<th>Strona zbierajca zasoby na otwartej licencji</th>
<th>https://archive.org/</th>
</tr>


<tr>
<th>BazHum</th>
<th>Repozytorium polskich artyku贸w. Darmowe i w otwartym dostpie</th>
<th>http://bazhum.muzhp.pl/</th>
</tr>



<tr>
<th>The Directory of Open Access Journals </th>
<th>Zbi贸r pism w otwartym dostpie </th>
<th>https://doaj.org/ </th>
</tr>



<tr>
<th> Centrum Informacji Naukowej i Biblioteka Akademicka U</th>
<th>Wyszukiwarka 藕r贸de </th>
<th>https://www.ciniba.edu.pl/ </th>
</tr>


<tr>
<th>The Central European Journal of Social Sciences and Humanities </th>
<th>Repozytorium artyku贸w. Darmowy i otwarty dostp </th>
<th>http://cejsh.icm.edu.pl/ </th>
</tr>


<tr>
<th>Central and Eastern European Online Library </th>
<th>Repozytorium artyku贸w </th>
<th>https://www.ceeol.com/ </th>
</tr>


<tr>
<th>Zasoby online BUW </th>
<th> </th>
<th>https://www.buw.uw.edu.pl/pl/online-resources/online-databases/ </th>
</tr>


<tr>
<th>E-naukowiec </th>
<th>Repozytorium artyku贸w i ksi偶ek </th>
<th>http://e-naukowiec.eu/ </th>
</tr>


<tr>
<th>Repozytorium Cyfrowe Instytut贸w Naukowych </th>
<th>Repozytorium artyku贸w </th>
<th>https://rcin.org.pl/dlibra </th>
</tr>


<tr>
<th>Wikiksi偶ki</th>
<th>Darmowe materiay naukowe</th>
<th>https://pl.wikibooks.org/wiki/Wikibooks:Strona_g%C5%82%C3%B3wna  </th>
</tr>


<tr>
<th>Platforma Otwartej Nauki</th>
<th>Repozytorium otwartej i darmowej wiedzy</th>
<th>http://pon.edu.pl/ </th>
</tr>
 

<tr>
<th>Scopus </th>
<th>Strona na kt贸rej mo偶na sprawdzi impact factor czasopism </th>
<th>https://www.scopus.com/home.uri </th>
</tr>



<tr>
<th>Web of science </th>
<th>Strona na kt贸rej mo偶na sprawdzi impact factor czasopism </th>
<th>http://webofknowledge.com  </th>
</tr>




	

</table>
 </span>
 
 
 

<b> Artykuy agregujce linki do przydatnych stron</b>

https://pl.wikipedia.org/wiki/Kategoria:Portale_naukowe 
	
	
	
Artyku o przydatnych stronach

https://medium.com/polish/37-najlepszych-stron-internetowych-do-nauki-nowych-rzeczy-18d2642ce821 
	

 Lista baz naukowych, wyszukiwarek, informator贸w (UJ)

https://bj.uj.edu.pl/zasoby-cyfrowe/ogolnodostepne-wyszukiwarki-bazy-zagraniczne 
	

Zasoby online BUW

https://www.buw.uw.edu.pl/zasoby-online/


Artyku z list przydatnych stron do nauki
https://lifegeek.pl/przydatne-strony/ 
	

 
Artyku na temat sztuki szukania artyku贸W naukowych
https://www.sztukaszukania.pl/2019/01/29/jak-szukac-artykulow-naukowych/ 
	



<b> Gdzie szuka oprogramowania?</b>


https://alternativeto.net/ 




<b> Reszta jeszcze nieuporzdkowana </b>
 
 


 
Portal Czasopism Naukowych (UJ)

https://www.ejournals.eu/ 
	

 
Portal Nauka Polska

http://www.nauka-polska.opi.org.pl/ 
	



 Przystanek Nauka (U)

https://przystaneknauka.us.edu.pl/  
	

 

https://nauka.uj.edu.pl/start  
	

 
Puls kosmosu 

https://www.pulskosmosu.pl/


 

strefa psyche 

https://www.swps.pl/strefa-psyche


Lek.Check

https://www.facebook.com/113957380786168/posts/119289410252965/?d=n  


	
Humanistyka medyczna

 https://www.facebook.com/humanistykamedyczna/  

 

https://naukawpolsce.pap.pl/aktualnosci/news%2C84944%2Cwkrotce-kolejne-odcinki-podcastow-biocentrum-edukacji-naukowej.html 
	
 


https://nowewyrazy.uw.edu.pl/linki.html 

 


<b> Serwisy informacyjne popularno-naukowe 叼</b>

<table>
<tr>
<th> </th>
<th> </th>
<th>https://dzienniknaukowy.pl/ </th>
</tr>




 

<tr>
<th>Nauka w Polsce (PAP) </th>
<th> </th>
<th>https://naukawpolsce.pap.pl </th>
</tr>

	

</table>
	

<b> Serwisy informacyjne popularno-naukowe </b>
 <table>
 <tr>
<th> </th>
<th> </th>
<th> </th>
</tr>

</table>


<b> Blogi popularno-naukowe 叼</b>

 <table>
<tr>
<th>Nauka to lubi </th>
<th> </th>
<th>https://www.naukatolubie.pl/ </th>
</tr>


<tr>
<th>Lista blog贸w naukowych </th>
<th> </th>
<th>https://ekulczycki.pl/warsztat_badacza/katalog-blogow-naukowych/   </th>
</tr>

	
<tr>
<th>Lista blog贸w naukowych </th>
<th> </th>
<th>http://www.zostanphd.pl/blogi-naukowe-share-week-2018/ </th>
</tr>	


<tr>
<th>Lista blog贸w naukowych </th>
<th> </th>
<th>https://naukawpolsce.pap.pl/aktualnosci/news%2C32436%2Cpolskie-popularnonaukowe-strony-blogi-kanaly-wideo-i-podcasty.html   </th>
</tr> 
 

<tr>
<th>Lista blog贸w naukowych </th>
<th> </th>
<th>https://www.crazynauka.pl/share-week-2019-czyli-dobre-blogi-ktore-wam-polecamy/  </th>
</tr>


<tr>
<th> Lista blog贸w naukowych</th>
<th> </th>
<th>https://www.dobreprogramy.pl/PREZESKIC/Popularyzacja-nauki-TOP-10-serwisow,88042.html  </th>
</tr>
	
<tr>
<th>Lista blog贸w naukowych </th>
<th> </th>
<th>https://www.totylkoteoria.pl/2019/01/ranking-polskich-blogow-naukowych-2018.html  </th>
</tr>


<tr>
<th>Lista blog贸w naukowych UKSW </th>
<th> </th>
<th>  https://biblioteka.uksw.edu.pl/pl/node/82  </th>
</tr>

</table>


	
<b> Blogi popularno-naukowe </b>
 <table>
 <tr>
<th> </th>
<th> </th>
<th> </th>
</tr>

</table>


<b> Kanay popularno-naukowe na youtube 叼</b>

 <table>


<tr>
<th> Nauka to lubi</th>
<th> </th>
<th>https://www.youtube.com/user/naukatolubie?app=desktop </th>
</tr>


<tr>
<th>Kasia gandor kana yt  </th>
<th> </th>
<th> https://www.youtube.com/channel/UCUercAwR2To1Zx6GA6ZP2TQ</th>
</tr>


<tr>
<th> Naukowy bekot </th>
<th> </th>
<th>https://www.youtube.com/channel/UC_7PqixGIdE-jjoHKMPYpGA </th>
</tr>


</table>



<b> Kanay popularno-naukowe na youtube </b>

 <table>

<tr>
<th>Veritasium </th>
<th> </th>
<th>https://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA </th>
</tr>



<tr>
<th>The Action Lab </th>
<th> </th>
<th>https://www.facebook.com/theactionlabofficial   </th>
</tr>


<tr>
<th>3Blue1Brown </th>
<th> </th>
<th>https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw  </th>
</tr>


<tr>
<th>Nature Video </th>
<th>Oficjalny kana pisma Nature </th>
<th>https://www.youtube.com/channel/UC7c8mE90qCtu11z47U0KErg </th>
</tr>


<tr>
<th>Minutephysics </th>
<th> </th>
<th>https://www.youtube.com/channel/UCUHW94eEFW7hkUMVaZz4eDg </th>
</tr>

<tr>
<th>Sciencephile the AI</th>
<th>Fizyka, kosmologia i memy </th>
<th>https://www.youtube.com/c/SciencephiletheAI</th>
</tr>



</table>



<span>




<b> Podkasty 叼</b></span>
 
<table>
<tr>
<th>Tu Centrum Nauki Kopernik  </th>
<th> </th>
<th> https://www.kopernik.org.pl/podcast-tu-centrum-nauki-kopernik</th>
</tr>



<tr>
<th>Dzia zagraniczny   </th>
<th>Rozmowy na temat region贸w wiata, o kt贸rych w du偶ych mediach si nie m贸wi </th>
<th>https://www.dzialzagraniczny.pl/  </th>
</tr>


<tr>
<th>Raport o stanie wiata </th>
<th>Rozmowy i reporta偶e na temat wiatowej kultury i polityki </th>
<th>https://raportostanieswiata.pl/  </th>
</tr>


<tr>
<th>Granice nauki </th>
<th> </th>
<th>https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9kMmQzOWI0L3BvZGNhc3QvcnNz </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://uni.wroc.pl/podcasty-naukowe/ </th>
</tr>

 
<tr>
<th> </th>
<th> </th>
<th> https://cwid.uw.edu.pl/podcast-nauka-nadaje/ </th>
</tr>


<tr>
<th>ScepTech  </th>
<th> </th>
<th> https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5hY2FzdC5jb20vcHVibGljL3Nob3dzL3NjZXB0ZWNo</th>
</tr>

  
<tr>
<th>Nauka XXI wieku  </th>
<th> </th>
<th> http://nauka.podkasty.info/</th>
</tr>

 
<tr>
<th> Crazy Nauka </th>
<th> </th>
<th>https://www.crazynauka.pl/ </th>
</tr>
	

<tr>
<th>Dekompresor Nauka  </th>
<th> </th>
<th> http://dekompresor.pl/nauka</th>
</tr>

 
<tr>
<th> </th>
<th> </th>
<th>http://Wszechnica.org.pl  </th>
</tr>

<tr>
<th> Radio Naukowe </th>
<th> </th>
<th>https://radionaukowe.pl/ </th>
</tr>

 
<tr>
<th>Babel. Rzeczpospolita Multi-Kulti (d. Lechistan)</th>
<th>Historia Polski poprzez pryzmat innych kultur </th>
<th>https://audycje.tokfm.pl/audycja/230,Babel-Rzeczpospolita-Multi-Kulti </th>
</tr>

	
<tr>
<th> 	SexAudycja</th>
<th> </th>
<th>	https://audycje.tokfm.pl/audycja/361,SexAudycja </th>
</tr>
	
	
<tr>
<th> 	 Klimat zmian </th>
<th> </th>
<th>	https://audycje.tokfm.pl/audycja/394,Klimat-zmian </th>
</tr>

	
<tr>
<th>	 Usugi Kosmiczne dla Ludnoci  </th>
<th> </th>
<th>	https://audycje.tokfm.pl/audycja/409,Uslugi-Kosmiczne-dla-Ludnosci </th>
</tr>

	
<tr>
<th>Przyjaciele Przyszoci </th>
<th>Rozmowy o technologiach i spoeczestwie przyszoci </th>
<th> https://anchor.fm/centrum-cyfrowe/message</th>
</tr>


</table>



<b> Podkasty </b>

<table>
<tr>
<th>Science Vs </th>
<th> </th>
<th>https://gimletmedia.com/shows/science-vs </th>
</tr>

<tr>
<th>The Anthropocene Reviewed </th>
<th> </th>
<th>https://www.wnycstudios.org/podcasts/anthropocene-reviewed  </th>
</tr>



<tr>
<th>Neuromantics </th>
<th> </th>
<th>https://www.willeaves.com/podcast </th>
</tr>

<tr>
<th>99% Invisible </th>
<th> </th>
<th>https://99percentinvisible.org/ </th>
</tr>

<tr>
<th>Nature Podcast </th>
<th> </th>
<th>https://www.nature.com/nature/articles?type=nature-podcast </th>
</tr>

<tr>
<th>Science Talk (Scientific American) </th>
<th> </th>
<th>https://www.scientificamerican.com/podcast/science-talk/ </th>
</tr>

<tr>
<th>Terrible Lizards </th>
<th> </th>
<th>https://terriblelizards.libsyn.com/ </th>
</tr>

<tr>
<th>British Museum Membercast </th>
<th> </th>
<th>https://www.britishmuseum.org/membership/membercasts </th>
</tr>

</table>


<b> Platformy dyskusji spoecznej</b> 

https://biennalewarszawa.pl/ 
	
	

 

https://www.mixcloud.com/radiokapital/radio-kapita%C5%82-godzina-szumu-3-marta-czy%C5%BC-i-urszula-zaj%C4%85czkowska/  
 
 
 
 Instagram: 
Kasiacoztymseksem 
https://www.instagram.com/kasia_coztymseksem/?hl=pl

I kulturaseksualna 
https://kulturaseksualna.pl/
 
 
 
https://kph.org.pl/wp-content/uploads/2017/11/Praktyczny-przewodnik-po-zdrowiu-LGBTI-dla-lekarzy.pdf 

https://kph.org.pl/publikacje_kph/ 

 
 
 <b> Cyfrowe muzea i galerie </b>
 
 http://cyfrowe.mnw.art.pl/
 
 
https://artmuseum.pl/pl/zasoby


https://artmuseum.pl/pl/archiwum


https://artmuseum.pl/pl/kolekcja


https://zacheta.art.pl/pl/kolekcja/katalog


https://www.europeana.eu/pl



https://zbiory.mnk.pl/en/home-page


https://www.wearemuseums.com/


https://www.paranoia-tv.com/en/


https://www.youtube.com/c/Pa%C5%84stwoweMuzeumEtnograficznewWarszawie/videos


https://muzea.malopolska.pl/pl/l


https://polona.pl/

<b> Strony fackcheckingowe</b>

https://fakenews.pl/


https://sprawdzam.afp.com/


https://demagog.org.pl/


https://misinforeview.hks.harvard.edu/


https://euvsdisinfo.eu/


https://www.stopfake.org/en/tag/disinformation-review/


https://schema.org/ClaimReview


https://developers.google.com/search/docs/data-types/factcheck


https://www.claimreviewproject.com/the-facts-about-claimreivew


https://www.storybench.org/how-claimreview-is-simplifying-the-process-of-fact-checking/


politifact.com


https://noodleremover.news/ 


fakeoff.org


stopfake.org


botometer.iuni.iu.edu


https://en.wikipedia.org/wiki/List_of_fake_news_websites


https://twitter.com/fakenews_buster?lang=en


 https://wid.org.pl/wp-content/uploads/E_wydanie-May-Leksykon-Postprawdy.pdf
 
 
 Media bias chart
 https://www.adfontesmedia.com/?v=402f03a963ba
 
 </span>
 
<table>
<tr>
<th> </th>
<th> </th>
<th> </th>
</tr>

</table>