---
title: "O co tutaj chodzi?"
site: distill::distill_website
output:
  distill::distill_article:
    toc: false
    includes:
      in_header:
      - hero-image.html
    theme: theme.css
---


<span style="margin-left:2em"> Cześć! Jesteśmy osobami zawodowo związanymi pracą naukową. Każde z nas poświęca się głównie swojej pracy i rozwojowi wewnątrz instytucji akademickich. Podczas niezobowiązujących rozmów zauważyliśmy, że widzimy podobne problemy w nauce - problemy komunikacji pomiędzy badaczami a resztą społeczeństwa, niedostateczne wykorzystywanie wiedzy naukowej i w rozwiązywaniu problemów społecznych. Zastanawialiśmy się czy jako naukowcy możemy w jakiś sposób przyłożyć się do rozwiązania tych problemów.   </span>

<span style="margin-left:2em"> W ten sposób narodził się ten projekt, który w obecnej fazie jest dla nas swojego rodzaju hobby, garażowym projektem. Chcielibyśmy wnieść swój głos do dyskusji o problemach nauki i być może zasugerować pewne rozwiązania. Zależy nam również na promowaniu wykorzystywania metod i wiedzy naukowej przez specjalistów nie-naukowców w ich codziennej pracy.   

<span style="margin-left:2em">Zaczniemy od publikowania przydatnych linków - baz danych, informatorów, stron popularyzujących naukę. Następnie zaczniemy publikować poradniki, pomagające poruszać się w świecie nauki. Na koniec uruchomimy większe projekty związane z nauką i jej popularyzowaniem. 


<span style="margin-left:2em">Do kogo kierujemy nasz projekt? Do osób zaczynających przygodę z nauką, do popularyzatorów/ek, influencerów/ek, osób zainteresowanych nauką i osób poszukujących wiedzy. 

<span style="margin-left:2em"> Naszym celem jest przede wszystkim redystrybucja nauki. To znaczy, że nie tyle chcemy ją <i>popularyzować</i>, co raczej przekazywać dalej, umieszczać w nowych kontekstach. Chcemy ułatwiać dostęp do nauki, pokazywać jak z niej korzystać i oferować wskazówki na temat tego, jak poruszać się w świecie nauki.  
 </span>


