---
title: ""
output: html_document
---

```{css, echo = FALSE}
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  padding: 15px;
}
```


## Strony {.tabset .tabset-dropdown}

### <span> <b> Gdzie zacz szukanie wiedzy, og贸lnoprzydatne serwisy</b>


<table style="width:100%">



<tr>
<th>
Google Scholar
</th>
<th>
Pierwsze miejsce w kt贸re nale偶y zajrze przy szukaniu artyku贸w naukowych
<th>
https://scholar.google.pl/ 
</th>
</tr>

<tr>
<th>Semantic Scholar</th>
<th>Alternatywa dla G.Scholar</th>

<th>https://www.semanticscholar.org/</th>
</tr>

<tr>
<th>Microsoft Academic</th>
<th>Alternatywa dla G.Scholar</th>

<th>https://academic.microsoft.com/home</th>
</tr>


<tr>
<th> Academia</th>

<th>Spoecznociowa baza artyku贸w</th>
<th>https://www.academia.edu/</th>
</tr>

<tr>
<th> ResearchGate</th>
<th> Spoecznociowa baza artyku贸w</th>
<th>https://www.researchgate.net/</th>
</tr>

<tr>
<th>Predatory Journals</th>
<th>Lista pism, kt贸rych nale偶y unika</th>

<th>https://predatoryjournals.com/journals/  </th>
</tr>

<tr>
<th>
Punktoza </th>
 
<th>Portal pozwalajcy sprawdzi aktualn punktacj czasopism wg list ministerialnych </th>
<th>https://punktoza.pl/ </th>
</tr>

<tr>
<th>Listy ministerialne punktowanych pism</th>
<th></th>
<th>https://listymnisw.pl/  </th>
</tr>

<tr>
<th>Orcid</th>
<th>Ka偶da osoba w nauce powinna zao偶y sw贸j wasny identyfikator ORCID</th>
<th>https://orcid.org/</th>

<tr>
<th>Otwarte Zasoby</th>
<th>Strona zbierajca zasoby na otwartej licencji</th>
<th>https://otwartezasoby.pl/ </th>
</tr>

<tr>
<th>Open Culture</th>
<th>Strona zbierajca zasoby na otwartej licencji</th>
<th>https://www.openculture.com/</th>
</tr>

<tr>
<th>Archive.com</th>
<th>Strona zbierajca zasoby na otwartej licencji</th>
<th>https://archive.org/</th>
</tr>


<tr>
<th>BazHum</th>
<th>Repozytorium polskich artyku贸w. Darmowe i w otwartym dostpie</th>
<th>http://bazhum.muzhp.pl/</th>
</tr>



<tr>
<th>The Directory of Open Access Journals </th>
<th>Zbi贸r pism w otwartym dostpie </th>
<th>https://doaj.org/ </th>
</tr>



<tr>
<th> Centrum Informacji Naukowej i Biblioteka Akademicka U</th>
<th>Wyszukiwarka 藕r贸de </th>
<th>https://www.ciniba.edu.pl/ </th>
</tr>


<tr>
<th>The Central European Journal of Social Sciences and Humanities </th>
<th>Repozytorium artyku贸w. Darmowy i otwarty dostp </th>
<th>http://cejsh.icm.edu.pl/ </th>
</tr>


<tr>
<th>Central and Eastern European Online Library </th>
<th>Repozytorium artyku贸w </th>
<th>https://www.ceeol.com/ </th>
</tr>

<tr>
<th>Repository of Centre for Open Science</th>
<th>Repozytorium artyku贸w </th>
<th>https://depot.ceon.pl/ </th>
</tr>

<tr>
<th>Baza AGRO</th>
<th>Repozytorium artyku贸w </th>
<th>http://agro.icm.edu.pl/</th>
</tr>



<tr>
<th>Zasoby online BUW </th>
<th> </th>
<th>https://www.buw.uw.edu.pl/pl/online-resources/online-databases/ </th>
</tr>


<tr>
<th>E-naukowiec </th>
<th>Repozytorium artyku贸w i ksi偶ek </th>
<th>http://e-naukowiec.eu/ </th>
</tr>


<tr>
<th>Repozytorium Cyfrowe Instytut贸w Naukowych </th>
<th>Repozytorium artyku贸w </th>
<th>https://rcin.org.pl/dlibra </th>
</tr>


<tr>
<th>Wikiksi偶ki</th>
<th>Darmowe materiay naukowe</th>
<th>https://pl.wikibooks.org/wiki/Wikibooks:Strona_g%C5%82%C3%B3wna  </th>
</tr>


<tr>
<th>Platforma Otwartej Nauki</th>
<th>Repozytorium otwartej i darmowej wiedzy</th>
<th>http://pon.edu.pl/ </th>
</tr>
 

<tr>
<th>Scopus </th>
<th>Strona na kt贸rej mo偶na sprawdzi impact factor czasopism </th>
<th>https://www.scopus.com/home.uri </th>
</tr>



<tr>
<th>Web of science </th>
<th>Strona na kt贸rej mo偶na sprawdzi impact factor czasopism </th>
<th>http://webofknowledge.com  </th>
</tr>


<tr>
<th>OpenAIRE </th>
<th>Wyszukiwarka artyku贸w w otwartym dostpie </th>
<th>https://explore.openaire.eu/</th>
</tr>

<tr>
<th>Zenodo</th>
<th>Wyszukiwarka artyku贸w w otwartym dostpie </th>
<th>https://zenodo.org/</th>
</tr>
	
<tr>
<th>Ibuk Libra</th>
<th>Czytelnia ksi偶ek z dostpem akademickim </th>
<th>https://libra.ibuk.pl/</th>
</tr>
	
	
<tr>	
<th>Free Learning List</th>
<th>Bogata lista stron edukacyjnych</th>
<th>https://freelearninglist.org/</th>
<tr>

</table>
 </span>
 
 
 

### <b> Artykuy agregujce linki do przydatnych stron</b>


<table>
<tr>
<th> </th>
<th> </th>
<th>https://pl.wikipedia.org/wiki/Kategoria:Portale_naukowe  </th>
</tr>

	
	
<tr>
<th>Artyku o przydatnych stronach </th>
<th> </th>
<th> https://medium.com/polish/37-najlepszych-stron-internetowych-do-nauki-nowych-rzeczy-18d2642ce821 
</th>
</tr>	


	
<tr>
<th> Lista baz naukowych, wyszukiwarek, informator贸w (UJ) </th>
<th> </th>
<th>https://bj.uj.edu.pl/zasoby-cyfrowe/ogolnodostepne-wyszukiwarki-bazy-zagraniczne 
 </th>
</tr>


	
<tr>
<th>Zasoby online BUW </th>
<th> </th>
<th> https://www.buw.uw.edu.pl/zasoby-online/</th>
</tr>




<tr>
<th>Artyku z list przydatnych stron do nauki </th>
<th> </th>
<th>https://lifegeek.pl/przydatne-strony/  </th>
</tr>




</table>
	



### <b> Gdzie szuka oprogramowania?</b>

<table>
<tr>
<th> </th>
<th> </th>
<th> https://alternativeto.net/ </th>
</tr>

</table>




### <b> Reszta jeszcze nieuporzdkowana </b>
 
<table>


<tr>
<th> Portal Czasopism Naukowych (UJ)</th>
<th> </th>
<th> https://www.ejournals.eu/ </th>
</tr>



	
<tr>
<th> Portal Nauka Polska</th>
<th> </th>
<th>http://www.nauka-polska.opi.org.pl/  </th>
</tr>
 



	

<tr>
<th> Przystanek Nauka (U)
 </th>
<th> </th>
<th> https://przystaneknauka.us.edu.pl/  
</th>
</tr>


	

<tr>
<th> </th>
<th> </th>
<th> https://nauka.uj.edu.pl/start  
</th>
</tr>

	
<tr>
<th> Puls kosmosu </th>
<th> </th>
<th> https://www.pulskosmosu.pl/</th>
</tr>
 





 
<tr>
<th>strefa psyche  </th>
<th> </th>
<th>https://www.swps.pl/strefa-psyche </th>
</tr>




<tr>
<th>Lek.Check </th>
<th> </th>
<th>
https://www.facebook.com/113957380786168/posts/119289410252965/?d=n  </th>
</tr>

 

<tr>
<th>Humanistyka medyczna </th>
<th> </th>
<th>  https://www.facebook.com/humanistykamedyczna/  </th>
</tr>
	


<tr>
<th>Instrat </th>
<th>Publikacje dotyczce ekonomii i klimatu </th>
<th>http://instrat.pl/publikacje/</th>
</tr>

<tr>
<th> </th>
<th> </th>
<th> https://naukawpolsce.pap.pl/aktualnosci/news%2C84944%2Cwkrotce-kolejne-odcinki-podcastow-biocentrum-edukacji-naukowej.html</th>
</tr>

<tr>
<th>Przydatny sowniczek do neuro</th>
<th> </th>
<th>http://fizyka.umk.pl/~duch/Wyklady/Mozg/Slowniczek.htm</th>
</tr>

	
 
<tr>
<th>Nowe Wyrazy (UW) </th>
<th>Portal monitorujcy nowe polskie sownictwo </th>
<th>https://nowewyrazy.uw.edu.pl/linki.html </th>
</tr>

 

</table>


### <b> Serwisy informacyjne popularno-naukowe 叼</b>

<table>
<tr>
<th>Dziennik Naukowy </th>
<th> </th>
<th>https://dzienniknaukowy.pl/ </th>
</tr>




 

<tr>
<th>Nauka w Polsce (PAP) </th>
<th> </th>
<th>https://naukawpolsce.pap.pl </th>
</tr>

	

</table>
	

### <b> Serwisy informacyjne popularno-naukowe </b>
 <table>
 <tr>
<th> </th>
<th> </th>
<th>Na razie pusto </th>
</tr>

</table>


### <b> Blogi popularno-naukowe 叼</b>

 <table>
<tr>
<th>Nauka to lubi </th>
<th> </th>
<th>https://www.naukatolubie.pl/ </th>
</tr>


<tr>
<th>Lista blog贸w naukowych </th>
<th> </th>
<th>https://ekulczycki.pl/warsztat_badacza/katalog-blogow-naukowych/   </th>
</tr>

	
<tr>
<th>Lista blog贸w naukowych </th>
<th> </th>
<th>http://www.zostanphd.pl/blogi-naukowe-share-week-2018/ </th>
</tr>	


<tr>
<th>Lista blog贸w naukowych </th>
<th> </th>
<th>https://naukawpolsce.pap.pl/aktualnosci/news%2C32436%2Cpolskie-popularnonaukowe-strony-blogi-kanaly-wideo-i-podcasty.html   </th>
</tr> 
 

<tr>
<th>Lista blog贸w naukowych </th>
<th> </th>
<th>https://www.crazynauka.pl/share-week-2019-czyli-dobre-blogi-ktore-wam-polecamy/  </th>
</tr>


<tr>
<th> Lista blog贸w naukowych</th>
<th> </th>
<th>https://www.dobreprogramy.pl/PREZESKIC/Popularyzacja-nauki-TOP-10-serwisow,88042.html  </th>
</tr>
	
<tr>
<th>Lista blog贸w naukowych </th>
<th> </th>
<th>https://www.totylkoteoria.pl/2019/01/ranking-polskich-blogow-naukowych-2018.html  </th>
</tr>


<tr>
<th>Lista blog贸w naukowych UKSW </th>
<th> </th>
<th>  https://biblioteka.uksw.edu.pl/pl/node/82  </th>
</tr>

</table>


	
### <b> Blogi popularno-naukowe </b>
 <table>
 <tr>
<th> </th>
<th> </th>
<th>Na razie pusto </th>
</tr>

</table>


### <b> Kanay popularno-naukowe na youtube 叼</b>

 <table>


<tr>
<th> Nauka to lubi</th>
<th> </th>
<th>https://www.youtube.com/user/naukatolubie?app=desktop </th>
</tr>


<tr>
<th>Kasia gandor kana yt  </th>
<th> </th>
<th> https://www.youtube.com/channel/UCUercAwR2To1Zx6GA6ZP2TQ</th>
</tr>


<tr>
<th> Naukowy bekot </th>
<th> </th>
<th>https://www.youtube.com/channel/UC_7PqixGIdE-jjoHKMPYpGA </th>
</tr>



<tr>
<th>Psychologia UMK </th>
<th>Wykady </th>
<th>https://www.youtube.com/channel/UCfPJKWnoDelXAm-25NEBMgg </th>
</tr>

<tr>
<th>IPI PAN </th>
<th>Wykady - Przetwarzanie jzyka naturalnego </th>
<th>https://www.youtube.com/channel/UC5PEPpMqjAr7Pgdvq0wRn0w </th>
</tr>

<tr>
<th>Centrum Nowoczesnoci Myn Wiedzy </th>
<th>Popularnonaukowe </th>
<th>https://www.youtube.com/channel/UCp2NkYqzGn4lbpoACOvEvlg </th>
</tr>

<tr>
<th>Oddzia Polskiej Akademii Nauk w Poznaniu </th>
<th>Wykady </th>
<th>https://www.youtube.com/channel/UCDfWTcT7AZay2Y4v-gn1dmQ </th>
</tr>

<tr>
<th> </th>
<th> </th>
<th> </th>
</tr>



</table>



### <b> Kanay popularno-naukowe na youtube </b>

 <table>

<tr>
<th>Veritasium </th>
<th> </th>
<th>https://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA </th>
</tr>



<tr>
<th>The Action Lab </th>
<th> </th>
<th>https://www.facebook.com/theactionlabofficial   </th>
</tr>


<tr>
<th>3Blue1Brown </th>
<th> </th>
<th>https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw  </th>
</tr>


<tr>
<th>Nature Video </th>
<th>Oficjalny kana pisma Nature </th>
<th>https://www.youtube.com/channel/UC7c8mE90qCtu11z47U0KErg </th>
</tr>


<tr>
<th>Minutephysics </th>
<th> </th>
<th>https://www.youtube.com/channel/UCUHW94eEFW7hkUMVaZz4eDg </th>
</tr>

<tr>
<th>Sciencephile the AI</th>
<th>Fizyka, kosmologia i memy </th>
<th>https://www.youtube.com/c/SciencephiletheAI</th>
</tr>

<tr>
<th>Real Engineering </th>
<th>In偶ynieria i technologia </th>
<th>https://www.youtube.com/channel/UCR1IuLEqb6UEA_zQ81kwXfg </th>
</tr>

<tr>
<th>NativLang </th>
<th>Lingwistyka, ciekawostki o jzykach </th>
<th>https://www.youtube.com/user/NativLang </th>
</tr>

<tr>
<th>Technology Connections </th>
<th>Technika, dziaanie urzdze </th>
<th>https://www.youtube.com/channel/UCy0tKL1T7wFoYcxCe0xjN6Q </th>
</tr>

<tr>
<th>Science News </th>
<th>Kosmologia, biologia, wieci ze wiata nauki </th>
<th>https://www.youtube.com/channel/UCBX5er6E37_yWB3gCM32p3g </th>
</tr>

<tr>
<th>Nature on PBS </th>
<th>Przyroda </th>
<th>https://www.youtube.com/channel/UCcBp_9YPyma4c3HTadmRJ3Q </th>
</tr>

<tr>
<th>Two Minute Papers </th>
<th>Wieci ze wiata AI, symulacji i grafiki </th>
<th>https://www.youtube.com/user/keeroyz </th>
</tr>

<tr>
<th>The British Museum </th>
<th>Historia </th>
<th>https://www.youtube.com/channel/UCvpQ-l09fCVxJd3urZbxzHg </th>
</tr>

<tr>
<th>The Oriental Institute </th>
<th>Historia </th>
<th> https://www.youtube.com/channel/UCitjN1GDlEVcLz-fAy5VIpg</th>
</tr>



</table>



<span>




### <b> Podkasty 叼</b></span>
 
<table>
<tr>
<th>Tu Centrum Nauki Kopernik  </th>
<th> </th>
<th> https://www.kopernik.org.pl/podcast-tu-centrum-nauki-kopernik</th>
</tr>



<tr>
<th>Dzia zagraniczny   </th>
<th>Rozmowy na temat region贸w wiata, o kt贸rych w du偶ych mediach si nie m贸wi </th>
<th>https://www.dzialzagraniczny.pl/  </th>
</tr>


<tr>
<th>Raport o stanie wiata </th>
<th>Rozmowy i reporta偶e na temat wiatowej kultury i polityki </th>
<th>https://raportostanieswiata.pl/  </th>
</tr>


<tr>
<th>Granice nauki </th>
<th> </th>
<th>https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9kMmQzOWI0L3BvZGNhc3QvcnNz </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://uni.wroc.pl/podcasty-naukowe/ </th>
</tr>

 
<tr>
<th> </th>
<th> </th>
<th> https://cwid.uw.edu.pl/podcast-nauka-nadaje/ </th>
</tr>


<tr>
<th>ScepTech  </th>
<th> </th>
<th> https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5hY2FzdC5jb20vcHVibGljL3Nob3dzL3NjZXB0ZWNo</th>
</tr>

  
<tr>
<th>Nauka XXI wieku  </th>
<th> </th>
<th> http://nauka.podkasty.info/</th>
</tr>

 
<tr>
<th> Crazy Nauka </th>
<th> </th>
<th>https://www.crazynauka.pl/ </th>
</tr>
	

<tr>
<th>Dekompresor Nauka  </th>
<th> </th>
<th> http://dekompresor.pl/nauka</th>
</tr>

 
<tr>
<th> </th>
<th> </th>
<th>http://Wszechnica.org.pl  </th>
</tr>

<tr>
<th> Radio Naukowe </th>
<th> </th>
<th>https://radionaukowe.pl/ </th>
</tr>

 
<tr>
<th>Babel. Rzeczpospolita Multi-Kulti (d. Lechistan)</th>
<th>Historia Polski poprzez pryzmat innych kultur </th>
<th>https://audycje.tokfm.pl/audycja/230,Babel-Rzeczpospolita-Multi-Kulti </th>
</tr>

	
<tr>
<th> 	SexAudycja</th>
<th> </th>
<th>	https://audycje.tokfm.pl/audycja/361,SexAudycja </th>
</tr>
	
	
<tr>
<th> 	 Klimat zmian </th>
<th> </th>
<th>	https://audycje.tokfm.pl/audycja/394,Klimat-zmian </th>
</tr>

	
<tr>
<th>	 Usugi Kosmiczne dla Ludnoci  </th>
<th> </th>
<th>	https://audycje.tokfm.pl/audycja/409,Uslugi-Kosmiczne-dla-Ludnosci </th>
</tr>

	
<tr>
<th>Przyjaciele Przyszoci </th>
<th>Rozmowy o technologiach i spoeczestwie przyszoci </th>
<th> https://anchor.fm/centrum-cyfrowe/message</th>
</tr>


</table>



### <b> Podkasty </b>

<table>
<tr>
<th>Science Vs </th>
<th> </th>
<th>https://gimletmedia.com/shows/science-vs </th>
</tr>

<tr>
<th>The Anthropocene Reviewed </th>
<th> </th>
<th>https://www.wnycstudios.org/podcasts/anthropocene-reviewed  </th>
</tr>



<tr>
<th>Neuromantics </th>
<th> </th>
<th>https://www.willeaves.com/podcast </th>
</tr>

<tr>
<th>99% Invisible </th>
<th> </th>
<th>https://99percentinvisible.org/ </th>
</tr>

<tr>
<th>Nature Podcast </th>
<th> </th>
<th>https://www.nature.com/nature/articles?type=nature-podcast </th>
</tr>

<tr>
<th>Science Talk (Scientific American) </th>
<th> </th>
<th>https://www.scientificamerican.com/podcast/science-talk/ </th>
</tr>

<tr>
<th>Terrible Lizards </th>
<th> </th>
<th>https://terriblelizards.libsyn.com/ </th>
</tr>

<tr>
<th>British Museum Membercast </th>
<th> </th>
<th>https://www.britishmuseum.org/membership/membercasts </th>
</tr>

</table>


### <b> Platformy dyskusji spoecznej</b> 


<table>


<tr>
<th>https://biennalewarszawa.pl/ </th>
</tr>
	

 
<tr>
<th>https://www.mixcloud.com/radiokapital/radio-kapita%C5%82-godzina-szumu-3-marta-czy%C5%BC-i-urszula-zaj%C4%85czkowska/  </th>
</tr>
 
<tr>
<th> Instagram: 
Kasiacoztymseksem 
https://www.instagram.com/kasia_coztymseksem/?hl=pl
</th>
</tr>

<tr>
<th>Kulturaseksualna 
https://kulturaseksualna.pl/
</th> 
</tr>


<tr> 
<th>https://kph.org.pl/wp-content/uploads/2017/11/Praktyczny-przewodnik-po-zdrowiu-LGBTI-dla-lekarzy.pdf </th>
</tr>

<tr>

<th>https://kph.org.pl/publikacje_kph/ </th>
</tr>

</table>
 
### <b> Cyfrowe muzea i galerie </b>
 
 
<table> 
 
<tr>
<th>http://cyfrowe.mnw.art.pl/</th>
</tr>
 
<tr>
<th>https://artmuseum.pl/pl/zasoby</th>
</tr>

<tr>
<th>https://artmuseum.pl/pl/archiwum</th>
</tr>

<tr>
<th>https://artmuseum.pl/pl/kolekcja</th>
</tr>

<tr>
<th>https://zacheta.art.pl/pl/kolekcja/katalog</th>
</tr>

<tr>
<th>https://www.europeana.eu/pl</th>
</tr>


<tr>
<th>https://zbiory.mnk.pl/en/home-page</th>
</tr>

<tr>
<th>https://www.wearemuseums.com/</th>
</tr>

<tr>
<th>https://www.paranoia-tv.com/en/</th>
</tr>

<tr>
<th>https://www.youtube.com/c/Pa%C5%84stwoweMuzeumEtnograficznewWarszawie/videos</th>
</tr>

<tr>
<th>https://muzea.malopolska.pl/pl/l</th>
</tr>

<tr>
<th>https://polona.pl/</th>
</tr>



### <b> Strony fackcheckingowe</b>
<table>

<tr>
<th> </th>
<th> </th>
<th> https://fakenews.pl/</th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://sprawdzam.afp.com/ </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th> https://demagog.org.pl/</th>
</tr>


<tr>
<th> </th>
<th> </th>
<th> https://misinforeview.hks.harvard.edu/</th>
</tr>


<tr>
<th> </th>
<th> </th>
<th> https://euvsdisinfo.eu/</th>
</tr>


<tr>
<th> </th>
<th> </th>
<th> https://www.stopfake.org/en/tag/disinformation-review/</th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://schema.org/ClaimReview </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://developers.google.com/search/docs/data-types/factcheck </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://www.claimreviewproject.com/the-facts-about-claimreivew </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th> https://www.storybench.org/how-claimreview-is-simplifying-the-process-of-fact-checking/</th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://politifact.com </th>
</tr>

<tr>
<th> </th>
<th> </th>
<th>https://noodleremover.news/  </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://fakeoff.org </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://stopfake.org </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://botometer.iuni.iu.edu </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://en.wikipedia.org/wiki/List_of_fake_news_websites </th>
</tr>


<tr>
<th> </th>
<th> </th>
<th>https://twitter.com/fakenews_buster?lang=en </th>
</tr>


<tr>
<th>Leksykon Postprawdy </th>
<th> </th>
<th>https://wid.org.pl/wp-content/uploads/E_wydanie-May-Leksykon-Postprawdy.pdf </th>
</tr>
 
 
 <tr>
<th> Media bias chart </th>
<th> </th>
<th> https://www.adfontesmedia.com/?v=402f03a963ba</th>
</tr>

</table>
 
 </span>
 
### <b> Pozyskiwanie grant贸w</b>
 
 
<table>
<tr>

<th>https://www.ncn.gov.pl/finansowanie-nauki/konkursy/typy</th>
 
</tr> 
 
</table>

### <b> Poradniki</b>
 
<table> 




<tr>
<th>Poradnik korzystania z Google Scholar </th>
<th> </th>
<th> https://pitt.libguides.com/googlescholar/searchtips
</th>
</tr>
 
 
<tr>
<th>Poradnik korzystania z Google Scholar </th>
<th> </th>
<th> https://www.wur.nl/en/article/How-to-use-Google-Scholar.htm</th>
</tr> 
 

 
<tr>
<th>Poradnik korzystania z Google Scholar </th>
<th> </th>
<th> https://guides.library.ucsc.edu/c.php?g=745384&p=5361954</th>
</tr> 
 

 
<tr>
<th> Poradnik korzystania z Google Scholar</th>
<th> </th>
<th> https://guides.library.illinois.edu/c.php?g=347668&p=2344602</th>
</tr> 
 


<tr>
<th>Poradnik korzystania z Google Scholar </th>
<th> </th>
<th> https://paperpile.com/g/google-scholar-guide/</th>
</tr>


	

<tr>
<th>Artyku na temat sztuki szukania artyku贸W naukowych </th>
<th> </th>
<th>https://www.sztukaszukania.pl/2019/01/29/jak-szukac-artykulow-naukowych/  </th>
</tr> 

</table>

<table>
<tr>
<th> </th>
<th> </th>
<th> </th>
</tr>

</table>